# Cloudflare Pages Configuration
name = "temp-email-frontend"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
publish = "dist"

[build.environment_variables]
NODE_VERSION = "18"

# Environment Variables for different environments
[env.production]
vars = { VITE_API_BASE_URL = "https://your-api-domain.com" }

[env.staging]
vars = { VITE_API_BASE_URL = "https://staging-api-domain.com" }

[env.development]
vars = { VITE_API_BASE_URL = "http://localhost:8787" }

# Custom domains (configure in Cloudflare dashboard)
# routes = [
#   { pattern = "temp-email.example.com", custom_domain = true }
# ]

# Pages Functions (if needed for API endpoints)
# [functions]
# directory = "functions"
